clean: true
source: source
destination: build
collections:
  courses:
    path: ./source/courses/*.md
    orderBy: date
markdown:
  smartypants: true
  gfm: true
  tables: true
permalinks:
  relative: true
  permalink: true
twig:
  directory: ./dev/twig
  view: base.twig
  cache: false
